name: Update package.json version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update package.json version
        run: |
          # Increment the patch version number in package.json
          npm version patch --no-git-tag-version
          # Commit the updated package.json file
          git add package.json
          git commit -m "Update package.json version"
          # Push the commit to the main branch
          git push origin main
