name: Update package.json version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update package.json version
      run: |
        # Increase patch version
        version=$(node -p "require('./package.json').version")
        new_version=$(echo $version | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
        node -e "fs.writeFileSync('./package.json', JSON.stringify({...require('./package.json'), version: '$new_version'}, null, 2))"

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore(version): bump version to ${new_version}"
        push: true
